export const AUTHENTICATE_USER_SUCCESS = 'AUTHENTICATE_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const SET_USERS = 'SET_USERS';

export const FETCH_RESOURCE_START = 'FETCH_RESOURCE_START';
export const FETCH_RESOURCE_FAIL = 'FETCH_RESOURCE_FAIL';
export const FETCH_RESOURCE_SUCCESS = 'FETCH_RESOURCE_SUCCESS';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const LOGOUT = 'LOGOUT';

export const FETCH_CURRENT_USER_WITHDRAWALS = 'FETCH_CURRENT_USER_WITHDRAWALS';
export const SET_WITHDRAWALS = 'FETCH_CURRENT_USER_WITHDRAWALS';
export const SET_FUND_VARIATIONS = 'SET_FUND_VARIATIONS';
export const SET_USER_FUND_VARIATIONS = 'SET_USER_FUND_VARIATIONS';
export const REMOVE_WITHDRAWAL = 'REMOVE_WITHDRAWAL';

export const SET_DASHBOARD = 'SET_DASHBOARD';
export const SET_GRAPHDATA = 'SET_GRAPHDATA';